In [5]:
## 导入需要的库
import torch

## 指定张量的数据类型和是否要计算梯度
B = torch.tensor((1,2,3),dtype=torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [6]:
A = torch.tensor((1,2,3))
A

tensor([1, 2, 3])

In [8]:
A.pow(3)

tensor([ 1,  8, 27])

In [4]:
B.pow(2)

tensor([1., 4., 9.], grad_fn=<PowBackward0>)

In [9]:
## 因为张量B是可计算梯度的，所以可以计算sum(B^2)的梯度
y  = B.pow(2).sum()
y

tensor(14., grad_fn=<SumBackward0>)

In [10]:
y.backward()
B.grad

tensor([2., 4., 6.])

In [14]:
## 创建具有特定大小的张量
D = torch.Tensor(2,3)
D

tensor([[9.2755e-39, 1.0837e-38, 8.4490e-39],
        [1.1112e-38, 1.0194e-38, 9.0919e-39]])

In [13]:
## 创建一个类型相似但尺寸不同的张量
E = [[1,2],[3,4]]
E = D.new_tensor(E)
print("D.dtype : ",D.dtype)
print("E.dtype : ",E.dtype)
E

D.dtype :  torch.float32
E.dtype :  torch.float32


tensor([[1., 2.],
        [3., 4.]])

In [19]:
## 创建一个类型相似但尺寸不同的张量
E = [[1,2],[3,4]]
E = D.new_tensor(E)
E

tensor([[1., 2.],
        [3., 4.]])

In [20]:
E.new_full((3,3), fill_value = 1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
A = torch.tensor((1,2,3))
A

tensor([1, 2, 3])

In [22]:
F = A.new_full((3,3), fill_value = 1)
F

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [23]:
D.new_empty((3,3))

tensor([[7.5306e-39, 8.4490e-39, 9.6428e-39],
        [1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39]])

In [30]:
torch.arange(1 ,10.0, step=2)

tensor([1., 3., 5., 7., 9.])

In [31]:
## 使用tensor.reshape()函数设置张量的尺寸
A = torch.arange(12.0).reshape(3,4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
## 使用torch.reshape()
torch.reshape(input = A,shape = (2,-1))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [34]:
## 使用.expand_as()方法拓展张量
C = torch.arange(6).reshape(2,3)
C

tensor([[0, 1, 2],
        [3, 4, 5]])

In [36]:
A = torch.arange(3)
A

tensor([0, 1, 2])

In [37]:
B = A.expand_as(C)
B

tensor([[0, 1, 2],
        [0, 1, 2]])

In [42]:
## 使用.repeat()方法拓展张量
D = B.repeat(2,2,2)
D

tensor([[[0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2]],

        [[0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2]]])